dir:
  reid : "/Users/curarpikt/Documents/datasets/ReID/MSMT17/bounding_box_train"
  smplx : "/Users/curarpikt/Documents/datasets/ReID_smplx/withyolo/MSMT17/bounding_box_train"
  annot: "/Users/curarpikt/Documents/datasets/ReID_annot/MSMT17/bounding_box_train"
  mask: "/Users/curarpikt/Documents/datasets/ReID_mask_8/MSMT17/bounding_box_train"
  background: "/Users/curarpikt/Documents/datasets/ReID_background_8/MSMT17/bounding_box_train"
  foreground: "/Users/curarpikt/Documents/datasets/ReID_foreground_8/MSMT17/bounding_box_train"
    

id_dataset: "msmt" # market_0002
visible : "visible"
path_cache: "./humandataset_msmt_train.pkl"
n_divide: 3

# path_cache: "/machangxiao/code/MIP-ReID/configs/datasets/MSMT17/humandataset_market_train.pkl"
