dir:
  reid : "/Users/curarpikt/Documents/datasets/ReID/MARS-v160809/bbox_train"
  smplx : "/Users/curarpikt/Documents/datasets/ReID_smplx/withyolo/MARS-v160809/bbox_train"
  annot: "/Users/curarpikt/Documents/datasets/ReID_annot/MARS-v160809/bbox_train"
  mask: "/Users/curarpikt/Documents/datasets/ReID_mask_8/MARS-v160809/bbox_train"
  background: "/Users/curarpikt/Documents/datasets/ReID_back_8/MARS-v160809/bbox_train"
  foreground: "/Users/curarpikt/Documents/datasets/ReID_fore_8/MARS-v160809/bbox_train"

id_dataset: "mars"
visible: "visible"
path_cache: "./configs/dataset/MARS-v160809/cache_mars_train"
n_divide: 28
