dir:
  reid : "/Users/curarpikt/datasets/ReID/Market-1501-v15.09.15/bounding_box_train"
  smplx : "/Users/curarpikt/datasets/ReID_smplx/withyolo/Market-1501-v15.09.15/bounding_box_train"
  annot: "/Users/curarpikt/datasets/ReID_annot/Market-1501-v15.09.15/bounding_box_train"
  mask: "/Users/curarpikt/datasets/ReID_mask_8/Market-1501-v15.09.15/bounding_box_train"
  background: "/Users/curarpikt/datasets/ReID_background_8/Market-1501-v15.09.15/bounding_box_train"
  foreground: "/Users/curarpikt/datasets/ReID_foreground_8/Market-1501-v15.09.15/bounding_box_train"
    

id_dataset: "market" # market_0002
visible : "visible"
path_cache: "./configs/dataset/Market-1501-v15.09.15/cache_market_train"
n_divide: 2
# path_cache: "/Users/curarpikt/Desktop/mxx/humandataset_market_train_0002_0665.pkl"
# path_cache: "/Users/curarpikt/Desktop/mxx/humandataset_market_train_0666_1500.pkl"

# path_cache: "/machangxiao/code/MIP-ReID/configs/datasets/Market-1501-v15.09.15/humandataset_market_train.pkl"
